# Praticando com NumPy

Este notebook tem como objetivo praticar operações com **arrays** utilizando a biblioteca **NumPy**.

## 1. Importando o NumPy

In [1]:
import numpy as np

# Verificando versão do NumPy
print(np.__version__)

2.0.2


## 2. Criando Arrays

In [18]:
# Criando arrays a partir de listas
lista = [1, 2, 3, 4, 5]
arr = np.array(lista)
print("Array criado:", arr)

# Criando arrays especiais
print("Zeros:", np.zeros((3,3)))
print("Ones:", np.ones((2,4)))
print("Arange:", np.arange(0,10,2))
print("Linspace:", np.linspace(0,1,5))
print("Identidade:", np.eye(4))

Array criado: [1 2 3 4 5]
Zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Identidade: [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## 3. Operações Matemáticas com Arrays

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print("Soma:", a + b)
print("Subtração:", a - b)
print("Multiplicação:", a * b)
print("Divisão:", a / b)
print("Potência:", a ** 2)

## 4. Indexação e Fatiamento

In [17]:
matriz = np.arange(1,13).reshape(3,4)
print("Matriz:\n", matriz)

print("Elemento [0,0]:", matriz[0,0])
print("Primeira linha:", matriz[0])
print("Primeira coluna:", matriz[:,0])
print("Submatriz:\n", matriz[1:,1:3])

Matriz:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Elemento [0,0]: 1
Primeira linha: [1 2 3 4]
Primeira coluna: [1 5 9]
Submatriz:
 [[ 6  7]
 [10 11]]


## 5. Propriedades dos Arrays

In [16]:
arr = np.arange(12).reshape(3,4)
print("Array:\n", arr)
print("Shape:", arr.shape)
print("Dimensões:", arr.ndim)
print("Tamanho:", arr.size)
print("Tipo de dados:", arr.dtype)

Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)
Dimensões: 2
Tamanho: 12
Tipo de dados: int64


## 6. Funções Úteis

In [ ]:
dados = np.random.randint(1,100,20)
print("Dados:", dados)
print("Média:", np.mean(dados))
print("Desvio padrão:", np.std(dados))
print("Mínimo:", np.min(dados))
print("Máximo:", np.max(dados))
print("Soma:", np.sum(dados))
print("Ordenado:", np.sort(dados))
print("Valores únicos:", np.unique(dados))

## 7. Exercícios Práticos

1. Crie uma matriz identidade 5x5.
2. Gere 100 números aleatórios entre 0 e 1 e calcule média e desvio padrão.
3. Crie uma matriz 10x10 com valores de 1 a 100.
4. Substitua todos os números pares dessa matriz por -1.
5. Encontre o maior valor e sua posição em uma matriz aleatória 5x5.

In [12]:
# Exercício 1
matriz = np.eye(5)

print("Matriz:\n", matriz)

Matriz:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# Exercício 2
numeros = np.random.randint(1,101, size=100)

# Calculo da média
print(np.mean(numeros))

# Calculo do Desvio Padrão
print(np.std(numeros))

48.21
30.405359724890616


In [29]:
# Exercício 3
matriz = np.arange(1, 101).reshape(10,10)

print("Matriz:\n", matriz)



Matriz:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [28]:
# Exercício 4
matriz = np.arange(1, 101).reshape(10,10)

print("Matriz default:\n", matriz)

matriz_nova = np.where((matriz % 2 == 0), -1, matriz)

print("\nMatriz com -1: \n", matriz_nova)

Matriz default:
 [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

Matriz com -1: 
 [[ 1 -1  3 -1  5 -1  7 -1  9 -1]
 [11 -1 13 -1 15 -1 17 -1 19 -1]
 [21 -1 23 -1 25 -1 27 -1 29 -1]
 [31 -1 33 -1 35 -1 37 -1 39 -1]
 [41 -1 43 -1 45 -1 47 -1 49 -1]
 [51 -1 53 -1 55 -1 57 -1 59 -1]
 [61 -1 63 -1 65 -1 67 -1 69 -1]
 [71 -1 73 -1 75 -1 77 -1 79 -1]
 [81 -1 83 -1 85 -1 87 -1 89 -1]
 [91 -1 93 -1 95 -1 97 -1 99 -1]]


In [34]:
# Exercício 5
matriz = np.random.rand(5,5)

print ("Matriz:\n", matriz)

print ("\nMaior valor da Matriz\n", np.max(matriz))
print("\nIndíce do maior valor (linha, coluna)\n", np.where(matriz == np.max(matriz)))

Matriz:
 [[0.32953836 0.17196164 0.52465287 0.29224633 0.9620081 ]
 [0.58172443 0.70711461 0.61564816 0.66137854 0.61829429]
 [0.1313704  0.71266895 0.81212203 0.33076038 0.90968796]
 [0.13062912 0.32338559 0.45493449 0.0453709  0.2511412 ]
 [0.08084599 0.16383807 0.6802121  0.36011213 0.22921848]]

Maior valor da Matriz
 0.9620081032812635

Indíce do maior valor (linha, coluna)
 (array([0]), array([4]))
